[tool.poetry]
name = "tilde.team.jwcook"
version = "0.0.1"
description = "tilde.team page for jwcook"
authors = ["Jordan Cook"]
license = "MIT"
readme = "README.md"
homepage = "https://tilde.team"

[tool.poetry.dependencies]
python                     = "^3.7"
furo                       = "^2022.6"
gruvboxsphinx              = ">=1.3"
linkify-it-py              = ">=2.0"
myst-parser                = ">=0.17"
sphinx                     = "^5.0.2"
sphinx-design              = ">=0.2"
sphinx-notfound-page       = ">=0.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
