[project]
name = 'jwcook.tilde.team'
requires-python = '>=3.10'
version = "0.1.0"
dependencies = [
    'furo~=2024.5',
    'linkify-it-py>=2.0',
    'myst-parser~=2.0',
    'pre-commit~=3.0',
    'sphinx~=6.2',
    'sphinx-autobuild>=2021.3',
    'sphinx-copybutton>=0.5',
    'sphinx-design>=0.6',
    'sphinx-notfound-page>=1.0',
    'sphinx-tags>=0.3',
]

# Placeholder to allow installing dependencies as if it were a package
[tool.setuptools]
packages = ['pages']

[tool.black]
skip-string-normalization = true
line-length = 100

[tool.isort]
profile = 'black'
line_length = 100
skip_gitignore = true
